version: "3"

services:
  web:
    volumes:
      - ..:/app
    build:
      context: ..
    image: "liveopex:0.1.0.dev"
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=docker
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:postgres@db/liveopex_dev
    expose:
      - "4000"
    networks:
      - prometheus-app
      - database-app
      - world
  db:
    image: "postgres"
    restart: always
    container_name: "liveopex-db"
    ports:
      - "5432:5432"
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres13
      - POSTGRES_DB=liveopex_dev
    expose:
      - "5432"
    networks:
      - database-app
      - world
  adminer:
    image: adminer
    restart: always
    ports:
      - "9080:8080"
    expose:
      - 9080
    networks:
      - database-app
      - world
volumes:
  pgdata:
networks:
  database-app:
    internal: true
